### PR TITLE
V0.1.0

### PR DESCRIPTION
**Pull request by diasdavid**
WIP

- [x] Get service worker to capture requests
- [x] Add js-ipfs in
- [x] Finish [Awesome WebWorker Endeavour](https://github.com/ipfs/js-ipfs/issues/725)

### CODE REVIEW

**Comment by diasdavid** [comment]
# Update

I'm now able to run successfully a js-ipfs node in a Service Worker and capture a request and make the fetch through js-ipfs 🌟 woot!

image

I'm not being successful though, on loading the second page and doing a request to the first-page domain and get that served by the service worker.

Instructions to try this out:

```
> git clone git@github.com:ipfs/ipfs-service-worker.git -b v0.1.0
> cd ipfs-service-worker 
> npm install
> npm link ipfs # you need to use the master version of js-ipfs until v0.24 is released
> cd /examples/use-from-another-page
> npm install
> npm run build
> npm i node-static -g
> static public+sw
# open your browser in localhost:8080
# refresh your page (for some reason, the service worker only activates on refresh)
# insert the hash in the box QmSiV9n9jofrEaWRjStCqVTspr4fLrvSNtmDRsfYuUtHHj
# click fetch
# voilá!
```

**Comment by diasdavid** [comment]
Next steps:

- Service Worker wise:
  - [ ] Understand why the page requires to be refreshed one time in order for the Service Worker to 
kick in
  - [ ] Figure out how to request from website on domain B an image served by service worker on domain A
- Feature wise:
  - [ ] Path support
  - [ ] Extract content types from file extensions
- [ ] Document the whole thing

**Comment by ilyaigpetrov** [comment]
@diasdavid, I tired to follow your instructions:
1. First line requires SSH key or something else. Cloned via https instead.
2. Port 8080 on localhost conflicts with ipfs daemon. Tried both:
  - stopping the daemon [1]
  - running command with other port [2] while daemon is running

#### Case [1]
Nothing happens, in logs:
```js
Fetch not in scope http://localhost:8080/
index.js:6 -> Registered the service worker successfuly
service-worker-bundle.js:49961 Handling fetch event for http://localhost:8080/ipfs/QmSiV9n9jofrEaWRjStCqVTspr4fLrvSNtmDRsfYuUtHHj
```

#### Case [2]
```js
Cannot read property 'files' of undefined
```

**Comment by RossRogers** [comment]
@ilyaigpetrov ,  `fetch` is a newer browser api.  Are you using a browser [that supports it](http://caniuse.com/#search=fetch)?

**Pull request merged**
